name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease

      # Upload artifact (APK file)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: JEE-Tracker-APK
          path: app/build/outputs/apk/release/app-release.apk
